version: 2

jobs:
  build:
    working_directory: ~/north

    docker:
    steps:
      - run: echo 127.0.0.1 node.dev | sudo tee -a /etc/hosts

      - checkout
      - restore_cache:
          keys:
          - dependencies-v1-{{ checksum "package.json" }}
          - dependencies-v1-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-v1-{{ checksum "package.json" }}

      - run: CI=true yarn test

      - run: yarn bundle && ./scripts/bundle-size.sh

      - run: yarn compile
